status = WARN
name = WeatherPipelineLogConfig

appender.console.type = Console
appender.console.name = Console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} [%t] %-5level %logger{36} - %msg%n

rootLogger.level = ERROR
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = Console

logger.spark.name = org.apache.spark
logger.spark.level = WARN
logger.spark.additivity = false
logger.spark.appenderRefs = console
logger.spark.appenderRef.console.ref = Console

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = WARN
logger.hadoop.additivity = false
logger.hadoop.appenderRefs = console
logger.hadoop.appenderRef.console.ref = Console

logger.jetty.name = org.eclipse.jetty
logger.jetty.level = WARN

logger.py4j.name = py4j
logger.py4j.level = WARN

